if (self.CavalryLogger) { CavalryLogger.start_js(["wwFcu"]); }

__d("AdsCMsDataCmsContentLoadFailureAction",["Laminar"],(function(a,b,c,d,e,f){"use strict";a=b("Laminar").__createAction(function(){return[]},function(){return[]},"ADS_CMS_CONTENT_LOAD_FAILURE");e.exports=a}),null);
__d("AdsCMsDataCmsContentLoadFailureActionFlux",[],(function(a,b,c,d,e,f){"use strict";e.exports={actionType:"ADS_CMS_CONTENT_LOAD_FAILURE"}}),null);
__d("AdsCMsDataCmsContentLoadedAction",["Laminar"],(function(a,b,c,d,e,f){"use strict";a=b("Laminar").__createAction(function(){return[]},function(){return[]},"ADS_CMS_CONTENT_LOADED");e.exports=a}),null);
__d("AdsCMsDataCmsContentLoadedActionFlux",[],(function(a,b,c,d,e,f){"use strict";e.exports={actionType:"ADS_CMS_CONTENT_LOADED"}}),null);
__d("AdsCMSDispatcher",["AdsCMsDataCmsContentLoadedAction","AdsCMsDataCmsContentLoadFailureAction","immutable"],(function(a,b,c,d,e,f){"use strict";a={dispatchLoadedCMS:function(a,c,d){a=b("immutable").Map().set(a,{cmsID:a,title:c,content:d});b("AdsCMsDataCmsContentLoadedAction").dispatch({data:a},{line:"30",module:"AdsCMSDispatcher.js"})},dispatchCMSLoadError:function(a){a=b("immutable").Map().set(a,{cmsID:a});b("AdsCMsDataCmsContentLoadFailureAction").dispatch({data:a},{line:"37",module:"AdsCMSDispatcher.js"})}};e.exports=a}),null);
__d("XAdsProductCMSContentAsyncController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/ads/ajax/product_cms_content/",{cms_id:{type:"FBID",required:!0}})}),null);
__d("AdsCMSDataLoader",["AdsCMSDispatcher","AsyncRequest","XAdsProductCMSContentAsyncController"],(function(a,b,c,d,e,f){"use strict";a={requestCMSContent:function(a){var c=b("XAdsProductCMSContentAsyncController").getURIBuilder().setFBID("cms_id",a).getURI();new(b("AsyncRequest"))().setURI(c).setAllowCrossPageTransition(!0).setOption("handleErrorAfterUnload",!0).setErrorHandler(function(c){b("AdsCMSDispatcher").dispatchCMSLoadError(a)}).send()}};e.exports=a}),null);
__d("AdsCMSDataManager",["AdsBaseDataManager","AdsCMSDataLoader"],(function(a,b,c,d,e,f){"use strict";__p&&__p();a=function(a){__p&&__p();babelHelpers.inheritsLoose(c,a);function c(){return a.apply(this,arguments)||this}var d=c.prototype;d.loadAll=function(a){var b=this;a.forEach(function(a){return b.load(a)})};d.load=function(a){b("AdsCMSDataLoader").requestCMSContent(a)};return c}(b("AdsBaseDataManager"));e.exports=new a()}),null);
__d("AdsCMSStore",["fbt","AdsBaseDataStore","AdsCMsDataCmsContentLoadedActionFlux","AdsCMsDataCmsContentLoadFailureActionFlux","AdsCMSDataManager","AdsLoadState_LEGACY","DOM"],(function(a,b,c,d,e,f,g){"use strict";__p&&__p();a=function(a){__p&&__p();babelHelpers.inheritsLoose(c,a);function c(){return a.apply(this,arguments)||this}var d=c.prototype;d.getDataManager=function(){return b("AdsCMSDataManager")};d.__getActionTypes=function(){return[b("AdsCMsDataCmsContentLoadFailureActionFlux").actionType,b("AdsCMsDataCmsContentLoadedActionFlux").actionType]};d.__onDispatch=function(a){a=a.action;switch(a.actionType){case b("AdsCMsDataCmsContentLoadedActionFlux").actionType:this.__handleData(a.data,b("AdsLoadState_LEGACY").LOADED);break;case b("AdsCMsDataCmsContentLoadFailureActionFlux").actionType:a=a.data.map(function(a){return Object.assign({},a,{title:g._("Error while loading CMS text").toString(),content:b("DOM").create("p",{},g._("There was an error while loading content text.").toString()),loadError:!0})});this.__handleData(a,b("AdsLoadState_LEGACY").LOADED);break}};return c}(b("AdsBaseDataStore"));c=new a();e.exports=c}),null);